project_name: octool
before:
  hooks:
    - go mod download
    - rm -rf dist
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -w
      - -s
    goos:
      - linux
      - darwin
    goarch:
      - amd64
release:
  github:
    owner: vapor-ware
    name: octool
  draft: false
  prerelease: auto
  name_template: "{{ .Version }}"
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - octool
    image_templates:
      - vaporio/octool:{{ .Tag }}
      - vaporio/octool:{{ .Major }}
      - vaporio/octool:latest
brews:
  - name: octool
    tap:
      owner: vapor-ware
      name: homebrew-formula
    commit_author:
      name: vio-bot
      email: 'marco+viogh@vapor.io'
    homepage: 'https://github.com/vapor-ware/octool'
    description: 'Simple tool to test/debug/diagnose connections to OpenConfig servers'
    test: |
      system "#{bin}/octool -h"
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
